---
title: "Las sílabas, las vocales y el ritmo"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview 

- This lesson continues previous talkbs about the syllable, vowels and 
expands to talk more about rhythm. 
- The exercises have been moved to "index_ex.Rmd" and can be used in 
class

## Reading

- de la Mota (2019)
- Focus
  - Las secciones **8.1 y 8.2** (pp 164-5) aportan una buena introducción al 
  tema
  - No es necesario dedicarle mucho tiempo a los distintos contornos 
  entonativos (pp 166-172), aunque sí es interesante
  - La sección **8.5** es la más importante para nuestra clase


## Videos

- For asynchronous teaching there are videos available here: 
- The lecture is divided into 3 videos using the following outline: 

1. Encadenamiento, el acento (duración)

    > Este módulo consiste en 3 vídeos. 
    Vamos a seguir hablando de la sílaba y las vocales y su relación con el 
    ritmo. 
    También vamos a explicar los fundamentos de la transcripción fonémica. 
    > 
    > En este primer vídeo vamos a ver un fenómeno íntimamente relacionado con 
    la sílaba y el ritmo, que es el encadenamiento 
    >
    > Recordad de otras lecciones que la estructura silábica preferida es CVCV. 
    El encadenamiento nos muestra como se intenta mantener esta estructura 
    no sólo dentro de una palabra, sino también entre palabras. 
    Entonces, tenemos palabras o secuencias de palabras como las de la lista 
    aquí. 
    >
    > A la derecha tenemos la silabificación. 
    Lo interesante aquí es notar que una secuencia como "el otro" generalmente 
    se silabifica como "e lo tro" y no "el...otro". 
    Este también es el caso para "e nel co che" y "a la mi go"
    >
    > La razón por la que este fenómeno del encadenamiento nos interesa es 
    porque es diferente con respecto a lo que suele pasar en inglés, done 
    es normal que intervenga otra consonante, un golpe de glotis, entre 
    palabras. 
    Es bastante difícil describir y producir un ejemplo de lo que es un golpe 
    de glotis. Es una consonante que muchas veces pasa desapercebida. 
    Incluyo en la presentación una canción de Katy Perry que creo que ilustra 
    bien lo que es y recomiendo que paréis esta grabación para escuchar y 
    apreciarla. 
    En todo caso, lo importante es entender que este sonido, el golpe de glotis, 
    es raro es español, por lo que el no nativo debe de evitarlo para mejorar 
    la pronunciación. 
    En pocas palabras lo que tiene que hacer es producir cada enunciado como 
    si fuera UNA palabra muy larga
    >
    > Y esto cómo se hace? Pues maximizando el arranque... es decir, manteniendo 
    la estructura silábica preferida entre palabras.
    > 
    > Este principio también se aplica a las secuencias vocálicas entre palabras 
    donde podemos formar diptongos si tenemos una vocal débil
    Observad las listas de abajo donde tenemos una vocal débil seguida de una 
    vocal fuerte cruzando una frontera léxica. 
    Entonces en habla lenta y cuidada, es totalmente posible que estas 
    secuencias se produzcan con dos vocales plenas, pero lo que es más común 
    es lo que vemos en la segunda columna, que representa habla más rápida. 
    Aquí la vocal débil se convierte en deslizada y forma un diptongo con la 
    vocal siguiente. 
    Entonces en lugar de "su a mi go" tenemos "sua migo", etc. etc. 
    >
    > Y esta idea también se aplica a un enunciado más largo...
    Una frase como "Mi amigo y yo fuimos a ver a un amigo" puede producirse 
    de manera lenta y cuidada, con una clara separación entre cada palabra... 
    No es que sea imposible, pero es muchísimo más normal que una frase como 
    ésta se articule con diptongos en los sitios donde suelen formarse en 
    español.
    >
    > Ahora quiero volver brevamente al tema del acento en español. 
    >
    > Específicamente queiro hablar de cómo el acento prosódico afecta al ritmo
    del español y del inglés en términos de la duración de las sílabas. 
    Por una parte, decimos que en español es una lengua de ritmo silábico en la 
    que todas las sílabas, tanto las átonas como las tónicas, cuentan con la 
    misma duración.
    Entonces en una palabra como "casa" la primera sílaba "ca" dura más o menos 
    lo mismo que "sa". 
    Por otra parte, decimos que el inglés es una lengua de ritmo acentual, lo 
    cual quiere decir que las sílabas tónicas son más largas que las sílabas 
    átonas. 
    Además, en las sílabas átonas vemos que las vocales reducen no sólo en 
    duración, sino también en calidad... o sea, muchas veces las vocales se 
    convierten en schwa. 
    Si tomamos como ejemplo las palabras "atom" y "atomic" podemos ver que la 
    primera sílaba de "atom", que "/ae/" es tónica y se produce con una vocal 
    plena. 
    En la palabra "atomic" el acento prosódico recae sobre la segunda sílaba, 
    /ta/, y vemos que esta sílaba es más larga que las otras. 
    Pero lo que es aún más interesante es el hecho de que la primera sílaba 
    ya no es /ae/, como en "atom" sino uh... uh ta mic... es una schwa. 
    >
    > Entonces, la conclusión lógica que podemos sacar de esta información es 
    que el angloparlante que quiere mejorar su pronunciación en español tiene 
    que evitar la reducción vocálica en las sílabas átonas... es decir, hay 
    que evitar la schwa. 
    Antes de terminar este vídeo, también quiero señalar que el estatus del 
    español como lengua de ritmo silábico es algo discutido entre los 
    fonólogos no todos están de acuerdo con esta caracterización. 
    Además, sabemos que la afirmación que todas las sílabas cuentan con la 
    misma duración independientemente del acento prosódico no es del todo 
    cierto. Es más bien una convención útil que nos sirve para describir el 
    español en términos generales con respecto otras lenguas, como el inglés. 

2. La transcripción

    > En este vídeo corto vamos a explicar lo básico de las transcripciones
    >
    > Para empezar, cabe mencionar que la idea fundamental detrás de la 
    transcripción es aportar una representación de la cadena hablada, tal 
    que otra persona puede leerla y tener una idea de lo que se articuló. 
    En nuestra clase veremos transcripciones fonológicas y fonéticas
    > 
    > La transcripción fonológica, también conocida como transcripción fonémica, 
    refleja una expresión dada en el plano de la lengua... esto quiere decir 
    que trabajamos al nivel fonológico y sólo nos preocupamos por los elementos 
    distintivos. En este caso distintivo es sinónimo de contrastivo... o sea 
    nos interesan los elementos que pueden cambiar el significado de una 
    palabra. 
    Como ejemplo, vamos a considerar la palabra "brevedad". 
    La transcripción fonológica aquí usa fonemas (notad que está entre barras) 
    y nos da una idea de una representación algo ideal de cómo se puede 
    pronunciar esta palabra
    > 
    > La transcripción fonética, en cambio, refleja un enunciado en el plano 
    del habla. Esto es diferente de la transcripción fonológica porque aquí 
    intervienen las variantes utilizadas por el que habla. 
    En otras palabras en una transcripción fonética, intentamos dar una 
    representación de exactamente lo que se dice con todo el detalle posible 
    de los sonidos que realmente se pronuncian.
    > 
    > Como ejemplo, vamos a considerar tres posibles articulaciones de la 
    palabra "brevedad". 
    En cada caso entendemos la misma idea, un sustantivo femenino que expresa 
    "la corta extensión o duración de una cosa, acción o suceso" pero podemos 
    ver que cada transcripción aporta una pronunciación un poco diferente. 
    Por ejemplo puedo decir "brevedadddd" con una aproximante sonora al final, 
    o "brevedath" con una fricativa interdental... incluso puedo eledir el 
    último segmento "breveda" y en cada caso se entiende que es la misma 
    palabra, pero la transcripción fonética me aporta más detalles de lo que 
    se pronuncia en realidad
    > 
    > Estamos empezando a desarrollar una idea algo más sofisticada de las 
    diferencias entre la fonética y la fonología. 
    Creo que esta imagen ayuda a ilustrar. 
    La parte de abajo representa la fonología. 
    Es un dibjo muy simple. Carece de detalles. Tenemos lo minimo para hacernos 
    una idea de lo que pasa. 
    La transcripción fonológica nos dice "take that you scoundrel" un mínimo 
    de información para que podamos entender lo que pasa. 
    La imágen de arriba, en cambio, representa la fonética y aporta mucho 
    detalle. 
    Algunos quizá dirían que hay demasiado detalle, que no es necesario. 
    En ambos casos nos hacemos una idea de lo ocurrido, pero aquí podemos 
    ver quién hace la acción, dónde están, etc. 
    En general no consideramos que un tipo de transcripción sea mejor que 
    otro... más bien aportan información diferente que puede ser útil en 
    función dse nuestros propósitos
    > 
    > Destacamos que la transcripción fonética puede ser de dos tipos: estrecha 
    si damos mucha información acerca de la articulación o ancha si proveemos 
    menos detalle. 
    Podemos pensar que es un poco cómo tener telescopios con diferente 
    resolución óptica. 
    Existen telescopios baratos que sirven para observar las estrellas desde la 
    casa y también está el telescopio Hubble que da para mucho más. 
    En esta clase usaremos transcripciones anchas, o sea no nos va a hacer falta 
    la resolución óptica del telescopcio hubble para los análisis que vamos a 
    hacer. 
    > 
    > Por ahora, es importante recordar que en las transcripciones, tanto 
    las fonológicas como las fonéticas, separamos las sílabas usando puntos 
    y marcamos las sílabas tónicas poniendo una pequeña barra vertical al 
    principio 

3. Las vibrantes y los fonemas 

    > En el último vídeo de este módulo vamos a hablar de dos sonidos vibrantes 
    y vamos resumir lo que sabemos acerca de los fonemas consonánticos 
    del español 
    >
    > Como bien sabemos, hay dos vibrantes en español: la vibrante simple y 
    la vibrante múltiple. 
    La vibrante simple tiene este nombre porque la punta de la lengua sube y 
    toca el cielo de la boca una vez durante su articulación. 
    La vibrante múltiple, en cambio, incluye varios toques. 
    Este hecho hace que los dos sonidos sean bastante diferentes acústicamente 
    y que presenten diferentes dificultades con respecto a la pronunciación. 
    Hablaremos de estos temas más adelante en el curso, pero por ahora vamos 
    a concentrarnos en la relación entre los dos sonidos y la ortografía. 
    Es decir, ¿cuál es la correspondia entre los dos sonidos vibrantes y las 
    letras?
    > 
    > Si consideramos la vibrante simple primero, sabemos que siempre se 
    representa ortográficamente mediante el grafema de la "ere"... o sea una 
    solo letra, y no hay otras posibilidades. 
    Ahora bien, si consideramos la vibrante múltiple, sabemos que ocurre 
    en las palabras que incluyen el grafema "ere" y también el dígrafo 
    "doble ere" o "erre". 
    > 
    > Entonces, siempre que tenemos más de una posibilidad, tenemos que saber 
    la distribución de los grafemas. En este caso el problema se resume de la 
    siguiente manera: cuando se trata de una vibrante múltiple, ¿cómo sabemos 
    si representamos este sonido ortográficamente mediante el grafema "ere" o 
    el dígrafo "doble ere"?
    > 
    > Resulta que la distribución no es demasiado compleja. 
    El grafema "ere" siempre representa el sonido de la vibrante múltiple 
    en dos contextos concretos: el primer contexto es al principio de palabra, 
    como el primer sonido de la palabra "rico" o "romántico". 
    El segundo contexto es después de una consonante. 
    La fonotáctica del español limita las posibilidades a "l", "n" o "s". 
    Es decir, si tenemos el grafema de la "ere" después de una "l", "n" o "s", 
    siempre se pronuncia como vibrante múltiple, como observamos en una 
    palabra como "alrededor". 
    Notad que este contexto es el que presenta más problemas para el no nativo. 
    Es un contexto fónico que dificulta la articulación. 
    En cualquier otro contexto, el grafema "ere" siempre se pronuncia como 
    vibrante simple y, como bien sabemos, el dígrafo "doble ere" SIEMPRE se 
    produce como vibrante múltiple. 
    >
    > Poco a poco vamos aumentando la cantidad de fonemas que hemos visto en 
    clase, ahora vamos a resumir los sonidos consonánticos. 
    > 
    > La tabla que véis a la izquierda presenta todos los fonemas consonánticos 
    del español. Aún no hemos visto todos estos símbolos, pero deberíais 
    reconocer muchos de ellos... otros quizá sean desconocidos porque 
    representan sonidos de variedades regionales. 
    Por ahora solo quiero señalar la distribución de colores: algunos de los 
    símbolos se encuentran dentro de casillas azules y otros dentro de 
    casillas moradas. 
    Las azules representan los sonidos sordos del español, es decir los sonido 
    que se producen sin vibración de las cuerdas vocales, y las moradas son 
    los sonidos sonoros... los que se producen con vibranción de las cuerdas 
    vocales. 
    En la próximas semanas empezaremos a estudiar la información presentada
    en los ejes de la tabla. 
    > 
    > A modo de repaso, aumentamos la lista de temas que hemos visto en clase 
    >
    > Tened en cuenta que toda esta información puede entrar en la primera 
    prueba de alguna forma.
    >
    > Aseguraos de estudiar cualquier cosa que no entendáis y hablad conmigo si
    aún tenéis dudas
