---
output: pdf_document
classoption: twocolumn, landscape
---

# Fito y fitipaldis

## Soldadito marinero

Él camina __________ que las prisas no son buenas,  
en su brazo ___________ con cuidado la chaqueta.  
Luego pasa por la calle donde los chavales juegan,  
él también quiso ser niño pero le _______ la guerra.  

Soldadito marinero conociste a una sirena  
de esas que dicen te quiero si ven la ________ llena.  
Escogiste a la mas ________ y a la menos __________,  
sin saber como ha venido te ha cogido la tormenta  

Él quería cruzar los mares y olvidar a su __________,  
la verdad no fue dificil cuando conoció a Mariela,  
que tenia los ojos verdes y el negocio entre las piernas.  
¡Hay que ver que __________ no te arrimas a una buena!  

Soldadito marinero conociste a una sirena  
de esas que dicen te quiero si ven la __________ llena  
Escogiste a las mas _________ y a la menos ________,  
sin saber como ha venido te ha cogido la tormenta.  

Después de un __________ malo, una mala _________,  
dime porqué estas buscando una ___________ en la arena. 

\newpage


# Fito y fitipaldis

## Soldadito marinero

Él camina __________ que las prisas no son buenas,  
en su brazo ___________ con cuidado la chaqueta.  
Luego pasa por la calle donde los chavales juegan,  
él también quiso ser niño pero le _______ la guerra.  

Soldadito marinero conociste a una sirena  
de esas que dicen te quiero si ven la ________ llena.  
Escogiste a la mas ________ y a la menos __________,  
sin saber como ha venido te ha cogido la tormenta  

Él quería cruzar los mares y olvidar a su __________,  
la verdad no fue dificil cuando conoció a Mariela,  
que tenia los ojos verdes y el negocio entre las piernas.  
¡Hay que ver que __________ no te arrimas a una buena!  

Soldadito marinero conociste a una sirena  
de esas que dicen te quiero si ven la __________ llena  
Escogiste a las mas _________ y a la menos ________,  
sin saber como ha venido te ha cogido la tormenta.  

Después de un __________ malo, una mala _________,  
dime porqué estas buscando una ___________ en la arena. 


