---
output: pdf_document
classoption: twocolumn, landscape, 12pt
---

# Fito y fitipaldis

## La casa por el tejado

Ahora sí, parece que ya empiezo a **________**  
Las cosas importantes aquí  
Son las que están detrás de la piel  
Y todo lo demás empieza donde acaban mis pies  
después de mucho tiempo **________**  
que hay cosas que mejor no aprender.  

El colegio poco me enseñó  
si es por **______** **________** nunca aprendo  

(**Estribillo**)  

a **________** el cielo con las manos  
a reír y a llorar lo que te canto  
a **________** mi alma rota  
a perder el miedo a **________** como un idiota  
y a empezar la casa por el tejado  
a poder dormir cuando tú no estás a mi lado  
menos mal que fui un poco granuja  
todo lo que sé me lo enseñó una bruja  

Ruinas. ¿no ves que por dentro estoy en ruinas?  
Mi cigarro va quemando **________**,  
tiempo que se convirtió en cenizas  
Raro. No digo diferente digo raro  
ya no sé si el mundo está al revés  
o soy yo el que está **________** abajo  

El colegio poco me enseñó  
si es por **______** **________** nunca aprendo  

**Estribillo**  

\newpage

# Fito y fitipaldis

## La casa por el tejado

Ahora sí, parece que ya empiezo a **________**  
Las cosas importantes aquí  
Son las que están detrás de la piel  
Y todo lo demás empieza donde acaban mis pies  
después de mucho tiempo **________**  
que hay cosas que mejor no aprender.  

El colegio poco me enseñó  
si es por **______** **________** nunca aprendo  

(**Estribillo**)  

a **________** el cielo con las manos  
a reír y a llorar lo que te canto  
a **________** mi alma rota  
a perder el miedo a **________** como un idiota  
y a empezar la casa por el tejado  
a poder dormir cuando tú no estás a mi lado  
menos mal que fui un poco granuja  
todo lo que sé me lo enseñó una bruja  

Ruinas. ¿no ves que por dentro estoy en ruinas?  
Mi cigarro va quemando **________**,  
tiempo que se convirtió en cenizas  
Raro. No digo diferente digo raro  
ya no sé si el mundo está al revés  
o soy yo el que está **________** abajo  

El colegio poco me enseñó  
si es por **______** **________** nunca aprendo  

**Estribillo**  
