---
title: "La sílaba, los diptongos y los hiatos"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Overview

- This lesson includes basic information regarding the syllable, diphthongs, 
and hiatuses
- The exercises/videos have been moved to "index_ex.Rmd" and can be used in 
class
- There is also extra information regarding syllabification under a 
generative framework


## Videos

- For asynchronous teaching there are videos available here: 
- The lecture is divided into 4 videos using the following outline: 

1. Intro, grafemas/dígrafos y fonemas

    > Este módulo consiste en 4 vídeos en los cuales vamos a hablar de la sílaba,
    los diptongos y los hiatos
    En este primer vídeo hablaremos de grafemas, dígrafos y fonemas
    >
    > Antes de empezar conviene recordar que la lingüística tiene muchas ramas 
    distintas. 
    Específicamente en esta clase hablamos de la fonética y la fonología, y 
    por tanto la unidad que más nos interesa, al menos por ahora, es el sonido
    >
    > Ahora bien, es importante que sepamos distinguir entre los grafemas/dígrafos 
    y los sonidos
    Los grafemas representan lo que comunmente conocemos como letras, es decir, 
    la "c", la "a" o la "l", por ejemplo. 
    En algunos casos se juntan dos grafemas para representar un solo sonido, 
    en estos casos se trata de un dígrafo, como cuando juntamos los grafemas 
    "c" y "hache" para formar el dígrafo "ch" que representa el sonido [tS], 
    como en la palabra "muchacho", o la doble "l" para representar el sonido [j] 
    en la palabra "llegar"
    >
    > En el alfabeto del español hay 27 grafemas y 3 dígrafos, o sea en total 
    contamos con 30 letras. 
    > 
    > Por otra parte, cuando queremos hablar de sonidos utilizamos el término 
    fonema
    Entonces para nuestros propósitos un fonema representa la unidad mínima de
    sonido
    > 
    > Es importante esta distinción entre sonidos y letras
    Cuando escribimos usamos grafemas y dígrafos
    Cuando hablamos producimos sonidos
    Y a veces queremos representar por escrito estos sonidos. 
    En estos casos vamos a usar el alfabeto fonético internacional (AFI) o IPA 
    en inglés (veréis que muchas veces en clase voy a decir simplemente IPA)
    > 
    > Entonces para poder distinguir entre grafemas y fonemas cuando escribamos en 
    esta clase vamos a poner los grafemas y los dígrafos entre comillas y los 
    fonemas entre barras oblicuas. 
    Por ejemplo aquí tenemos el grafema "a" entre comillas y después el fonema, 
    es decir el sonido /a/ entre barras
    A estas alturas del semestre puede parecer una convención quizá un poco rara 
    o poco relevante, pero vamos a ver más adelante que es bastante importante
    Sobre todo porque vamos a ver que muchas veces en la fonética y fonología no 
    nos interesa la ortografía, pero necesitamos una manera de poder distinguir 
    entre letras y sonidos

2. La sílaba y el silabeo

    > En este vídeo vamos a hablar de la sílaba, sus componentes y la división 
    silábica
    > 
    > El silabeo o la silabificación se refiere a cómo dividimos una palabra dada 
    por sílabas
    Todo el mundo tiene algo de intuición acerca de la cantidad de sílabas que 
    tienen las palabras que conocen pero lo cierto es que no siempre nos ponemos 
    de acuerdo
    De todas maneras sí podemos llegar a un acuerdo con respecto a los 
    componentes que forman las sílabas
    Por ejemplo, todas las sílabas tienen un núcleo
    En español el núcleo puede ser una vocal o un diptongo (hablaremos de los 
    diptongos en el siguiente vídeo)
    Alrededor del núcleo suele haber consonantes
    > 
    > En español (y la mayoría de las lenguas) hay una estructura sílabica 
    que es más común
    O sea es una que observamos muchísmo más que otras
    > 
    > Esta configuración es la secuencia consonante-vocal-consonante-vocal
    Aúnque sea obvio, aquí la "c" significa consonante y la "v" significa vocal
    > 
    > Si consideramos algunas palabras comunes, como "casa" o "boca", podemos 
    observar esta estructura CVCV
    > 
    > Ahora bien, el hecho de que CV sea más común no quiere decir que no haya 
    otras opciones
    Al contrario, el lexicon del español está repleto de contraejemplos como 
    podemos ver aquí en el caso de "aereo" que cuenta con tres sílabas compuestas 
    de una sola vocal.... o la palabra "algo", cuya primera sílaba cuenta con 
    una vocal seguida por una consonante
    > 
    > En fin, no sería ni divertido ni interesante memorizar todas las posibles 
    configuraciones de sílabas en una lengua, pero sí podemos servirnos de 
    algunos patrones comunes, como CVCV, para poder explicar ciertos fenómenos 
    fonológicos que veremos después
    > 
    > Entonces ¿cómo se forma una sílaba?
    > 
    Como he mencionado hace poco, cada sílaba tiene que tener un núcleo y 
    en español siempre se trata de un núcleo vocálico
    > 
    > A la izquierda del núcleo, opcionalmente puede haber una consonante que 
    llamamos "cabeza"
    También nos referimos a esta posición dentro de la sílaba como "ataque" o 
    "arranque"
    > 
    > A la derecha del núcleo es común que apareza una consonante en la posición 
    de "coda"
    Veremos que las codas son muy interesantes en español ya que muchas cosas 
    divertidas pasan en esta posición
    > 
    > Podemos utilizar el término "rima" para referirnos al núcleo y coda a la 
    vez
    > 
    > Ahora que sabemos cuáles son los componentes de la sílaba, estamos casi 
    listos empezar a silabificar algunas palabras, pero antes es importante 
    saber los grupos consonánticos permitidos en español
    ¿Qué es un grupo consonántico?
    Pues es una serie de dos o más consonantes que pueden combinarse dentro de 
    una sílaba... o sea no todas las combinaciones son posibles
    Entonces lo fundamental para poder silabificar prácticamente cualquier 
    palabra en español es saber cuáles son los grupos consonánticos permitidos
    > 
    > La combinaciones permitidas en posición de ataque en español son las 
    siguientes: 
    notad que en ambas cajas se trata de una primera consante más otra consonante 
    líquida (el término "líquida" se refiere a una lateral o una vibrante, es 
    decir la "l" y la "r")
    La única diferencia entre las dos cajas es que la "t" y la "d" pueden 
    combinarse con la vibrante "erre" y esta combinación no es posible con la 
    "ele"
    > 
    > Aquí tenéis ejemplos de palabras que contienen los 12 grupos consonánticos 
    permitidos en posición de ataque en español
    La razón por la que esta información es útil a la hora de silabificar una 
    palabra es porque cualquier combinación de consonantes entre vocales, que no 
    sea un grupo consonántico permitido, siempre se separa y nunca inicia una 
    sílaba

3. Los monoptongos, los diptongos y los hiatos

    > En este vídeo vamos a hablar de los monoptongos, los diptongos y los hiatos
    > 
    > Empecemos por los monoptongos
    Un monoptongo es una vocal que aparece sola dentro de una sílaba, 
    lo importante del monoptongo es que la articulación y las características 
    acústicas no cambian durante su producción
    Por ejemplo, en la tabla de abajo vemos tres columnas
    La columna de la izquierda tiene ejemplos de palabras con monoptongos
    Las palabras aparecen entre comillas porque estamos viendo grafemas
    Los grafemas en rojo representan monoptongos
    Esto lo podemos apreciar aún más en la columna de en medio donde vemos 
    la silabificación de estas palabras y podemos comprobar que, efectivamente, 
    cada sílaba cuenta con solamente una vocal
    La última columna de la derecha aporta una transcripción fonémica de las 
    palabras, es decir, una representación mediante símbolos de la pronunciación 
    de estas palabras
    Fijaos que vemos algunos caracteres del alfabeto fonético internacional 
    que no se corresponden con los grafemas de la primera columna
    > 
    > Un diptongo, en cambio, se caracteriza por tener una secuencia de dos vocales 
    que se encuentran en una sílaba
    El diptongo está compuesto por una vocal pura y una deslizada (hablaremos de 
    las deslizadas en breve)
    Por ejemplo, en la tabla de abajo de nuevo vemos tres columnas
    La columna de la izquierda tiene ejemplos de palabras con diptongos
    Resalto otra vez que las palabras aparecen entre comillas porque se trata de 
    una representación ortográfica mediante grafemas
    Los grafemas en rojo representan diptongos
    Como en el caso anterior, la siguiente columna incluye la silabificación de 
    estas palabras y vemos que cada sílaba cuenta con dos vocales
    La última columna contiene transcripciones fonéticas de estas palabras
    Notad que en cada caso una de las vocales del diptongo cuenta con una 
    diacrítica debajo, una media lunita, que nos indica que es una deslizada
    > 
    > Vale la pena destacar que podemos distinguir entre tres tipos de diptongos: 
    Vamos a clasificarlos de acuerdo a las vocales que contengan
    > 
    > Por una parte tenemos diptongos crecientes, que cuentan con una vocal débil 
    en posición inicial
    luego están los diptongos decrecientes, que tienen la vocal débil en posición 
    final 
    y por último tenemos los diptongos acrecientes, que consisten en dos vocales 
    débiles juntas
    > 
    > Por razones obvias conviene entender qué significa que una vocal sea 
    "débil"
    Aquí vemos representado en dos dimensiones el espacio vocálico del español 
    (fijaos que estamos hablando de sonidos y por eso vemos fonemas)
    > 
    > Vamos a incluir dos ejes, un eje vertical y otro horizontal
    > 
    > Ahora podemos destacar las vocales débiles 
    > 
    > que se encuentran arriba, que son la /i/ y la /u/
    > 
    > Las vocales que están fuera de la caja roja se consideran vocales fuertes
    > 
    > Igual os estáis preguntando por qué decimos que algunas vocales son débiles 
    y otras fuertes... pues tiene que ver con la energía que tienen, la cual 
    se correlaciona con la apertura de la boca
    > 
    > Cuando producimos las vocales /i/ y /u/ tenemos la boca más cerrada, y por 
    esta razón también hay gente que dice que son vocales "cerradas". 
    Las vocales /e/, /a/ y /o/, en cambio, se articulan con la boca más abierta, 
    y como os podéis imaginar, también hay gente que les dice vocales abiertas
    > 
    > y como acabo de mencionar, la apertura bucal se correlaciona con la energía.
    Es una simplificación pero podemos decir que cuanto más abierta la vocal, más 
    energía tiene y de ahí usamos términos como "débil" y "fuerte"
    > 
    > Aquí tenemos los diptongos crecientes
    La columna de la izquierda nos enseña la combinación de vocales en grafemas
    La columna de en medio proporciona un ejemplo de una palabra que tiene esta
    combinación y la última columna aporta una transcripción fonética del 
    diptongo
    Fijaos que en todos los casos el diptongo comienza con una vocal débil y 
    en la transcripción se refleja este hecho mediante la diacrítica que tiene 
    justo debajo, que indica que es una deslizada (volveremos sobre este tema en 
    un par de minutos)
    > 
    > pero recordad que este tipo de diptongo, un diptongo creciente, comienza 
    con una vocal débil/cerrada/que tiene menos energía y termina con una vocal 
    fuerte/abierta/que tiene más energía 
    > 
    > En los diptongos decrecientes vemos que la situación es al revés
    Es decir, el diptongo comienza con una vocal fuerte/abierta y termina con 
    una vocal débil/cerrada
    De nuevo, esto se ve reflejado en la transcripción fonética, la columna de la 
    derecha, mediante la media lunita que se encuentra debajo de la deslizada.
    > 
    > En todos estos casos el diptongo decreciente comienza con una vocal 
    fuerte/abierta/que tiene más energía y termina con una vocal 
    débil/cerrada/que tiene menos energía 
    > 
    > Por último tenemos los diptongos acrecientes
    Estos diptongos consisten en dos vocales débiles 
    y en estos casos puede ser un poco más difícil determinar cuál es la vocal 
    plena y cuál es la deslizada, pero nos preocuparemos por eso más adelante
    > 
    > Lo importante es saber que en estos casos el diptongo empieza y termina con 
    una vocal débil o cerrada y la energía no cambia mucho
    > 
    > Ahora, llevo toda esta presentación hablando de deslizadas sin explicar lo 
    son. 
    Podemos pensar que son como variantes de las vocales plenas /i/ y /u/ que 
    son aún más débiles, cuentan con una duración más corta y nunca aparecen 
    solas. 
    Son como los hermanos pequeños de las vocales /i/ y /u/.
    Para nuestros propósitos vamos a decir que las vocales plenas /e/, /a/ y /o/ 
    no tienen variantes deslizadas
    > 
    > Ahora vamos a fijar nuestra atención en los hiatos
    > 
    > Un hiato, a diferencia de un diptongo, consiste en una secuencia de dos 
    vocales seguidas que se separan de dos sílabas distintas
    La columna de la izquierda aporta ejemplos de palabras que contienen hiatos
    En rojo vemos la secuencia de interés y si nos fijamos en la columna de en 
    medio vemos que en ambos casos las vocales en rojo aparecen en sílabas 
    diferentes
    Si analizamos la transcripción fonémica podemos sacar una generalización 
    importante, que es que en ambos casos tenemos secuencias de dos vocales 
    fuertes/abiertas
    > 
    > Esto es cierto en la gran mayoría de los hiatos (pero hablaremos de 
    algunas excepciones importantes más adelante)
    Resumiendo, podemos decir que los monoptongos involucran una de las 5 vocales 
    del español, no importa cuál, dentro una sílaba
    Los diptongos, en cambio, combinan al menos una vocal débil con cualquier 
    otra vocal también dentro de la misma sílaba
    y en los hiatos, en la mayoría de los casos, se trata de cualquier 
    combinación de vocales no débiles 
    (hablaremos las excepciones en el siguiente módulo)

4. Inglés vs. español  

    > En este último vídeo del módulo vamos a destacar algunas diferencias 
    entre el inglés y el español con respecto a las vocales
    > 
    > Para empezar vale la pena notar que el sistema vocálico del inglés es 
    muchísmo más grande que el del español, pues puede haber entre 11 y 14 
    vocales más los diptongos según la variedad
    > Además, las vocales del inglés tienden a  diptongizarse, incluso cuando en 
    teoría no tiene por qué haber un diptongo y esto puede ocurrir en el interior 
    de la palabra y también hacia el final
    > Otra característica del inglés que llama la atención es que algunas 
    vocales se someten a un proceso fonológico de reducción cuando se 
    encuentran en una sílaba átona... específicamente se reducen a shwa
    > Las vocales del español, en cambio, no presentan diptongación cuando no 
    corresponde y no suele haber reducción vocálica en las sílabas átonas
    >
    > Aquí vemos las 11 vocales del inglés californiano... otras variedades del 
    inglés cuentan con aún más vocales
    > 
    > Si comparamos con las vocales del inglés, podemos destacar que las 
    vocales del español suelen tener una duración más corta y se articulan con 
    más tensión bucal
    > 
    > Y cuando digo más tensión en la boca me refiero a los músculos que se 
    utilizan a la hora de articular las vocales del español
    > Esto supone un reto al cual el angloparlante se tiene que enfrentar para 
    mejorar su pronunciación en español 
    > 
    > Aquí observamos el espacio vocálico del español. 
    Del tirón vemos que hay menos vocales con respecto al inglés y hay más 
    espacio entre ellas
    > Aprender el sistema vocálico de otra lengua es difícil ya de por sí 
    pero lo cierto es que el reto es diferente según la lengua nativa del 
    aprendiz
    > El hispanoparlante, por ejemplo, suele tener dificultades a la hora de 
    distinguir entre todas las vocales del inglés. 
    > El angloparlante, por su parte, tiene más dificultades con la precisión 
    ya que tiene que limitar las opciones que tiene a las 5 vocales del español 
    > 
    > Si nos fijamos en esta imagen de una persona pronunciando la vocal /i/, 
    podemos ver que la boca está casi cerrada y los labios están esitrados
    > 
    > Para articular la /e/, la boca abre ligeramente y los labios siguen 
    estando estirados
    > 
    > Luego para producir una /a/, vemos que la boca está aún más abierta y 
    los labios ya no están estirados
    > 
    > Ahora la boca vuelve a cerrarse para producir una /o/ y los labios se 
    redondean
    > 
    > Por último, la producción de la /u/ requiere que la boca esté casi 
    cerrada de nuevo y que los labios sigan redondeados
    > 
    > A modo de concluir este módulo, vamos a repasar algunos de los 
    conceptos que hemos visto: 
    Primero, definimos la lingüística y destacamos las distintas ramas
    Luego distinguimos entre los grafemas/dígrafos por una parte y los fonemas 
    por otra... (es decir, las letras y los sonidos)
    Pasamos a comentar la composición de la sílaba y los grupos consonantícos 
    posibles en español
    Después, hablamos de los monoptongos, los tres tipod de diptongos y los hiatos 
    y por último vimos algunas de las diferencias entre las vocales del inglés 
    y las del español 
